Task - 1: Unit Conversion Program

In [ ]:
def convert_units():
    """
    Converts between different units of measurement.
    Supports length (meters to feet and vice versa),
    weight (kilograms to pounds and vice versa),
    and volume (liters to gallons and vice versa).
    """
    def meters_to_feet(meters):
        return meters * 3.28084

    def feet_to_meters(feet):
        return feet / 3.28084

    def kilograms_to_pounds(kg):
        return kg * 2.20462

    def pounds_to_kilograms(pounds):
        return pounds / 2.20462

    def liters_to_gallons(liters):
        return liters * 0.264172

    def gallons_to_liters(gallons):
        return gallons / 0.264172

    while True:
        print("\nChoose conversion type:")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")
        print("4. Exit")

        choice = input("Enter choice (1/2/3/4): ")

        if choice == "1":
            print("Choose conversion subtype:")
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            sub_choice = input("Enter choice (1/2): ")
            value = float(input("Enter value to convert: "))
            if sub_choice == "1":
                result = meters_to_feet(value)
                print(f"{value} meters is equal to {result} feet.")
            elif sub_choice == "2":
                result = feet_to_meters(value)
                print(f"{value} feet is equal to {result} meters.")
            else:
                print("Invalid choice.")

        elif choice == "2":
            print("Choose conversion subtype:")
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            sub_choice = input("Enter choice (1/2): ")
            value = float(input("Enter value to convert: "))
            if sub_choice == "1":
                result = kilograms_to_pounds(value)
                print(f"{value} kilograms is equal to {result} pounds.")
            elif sub_choice == "2":
                result = pounds_to_kilograms(value)
                print(f"{value} pounds is equal to {result} kilograms.")
            else:
                print("Invalid choice.")

        elif choice == "3":
            print("Choose conversion subtype:")
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            sub_choice = input("Enter choice (1/2): ")
            value = float(input("Enter value to convert: "))
            if sub_choice == "1":
                result = liters_to_gallons(value)
                print(f"{value} liters is equal to {result} gallons.")
            elif sub_choice == "2":
                result = gallons_to_liters(value)
                print(f"{value} gallons is equal to {result} liters.")
            else:
                print("Invalid choice.")

        elif choice == "4":
            print("Exiting the program. Goodbye!")
            break

        else:
            print("Invalid choice.")

convert_units()



Choose conversion type:
1. Length
2. Weight
3. Volume
4. Exit
Enter choice (1/2/3/4): 1
Choose conversion subtype:
1. Meters to Feet
2. Feet to Meters
Enter choice (1/2): 1
Enter value to convert: 222
222.0 meters is equal to 728.34648 feet.

Choose conversion type:
1. Length
2. Weight
3. Volume
4. Exit
Enter choice (1/2/3/4): 4
Exiting the program. Goodbye!


Task - 2: Mathematical Operations on a List of Numbers


In [ ]:
def math_operations():
    """
    Performs various mathematical operations on a list of numbers.
    Supports finding the sum, average, maximum, and minimum of the numbers.
    """
    def calculate_sum(numbers):
        return sum(numbers)

    def calculate_average(numbers):
        return sum(numbers) / len(numbers)

    def find_maximum(numbers):
        return max(numbers)

    def find_minimum(numbers):
        return min(numbers)

    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter choice (1/2/3/4): ")
    try:
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))
    except ValueError:
        print("Invalid input. Please enter numeric values.")
        return

    if choice == "1":
        result = calculate_sum(numbers)
        print(f"Sum: {result}")
    elif choice == "2":
        result = calculate_average(numbers)
        print(f"Average: {result}")
    elif choice == "3":
        result = find_maximum(numbers)
        print(f"Maximum: {result}")
    elif choice == "4":
        result = find_minimum(numbers)
        print(f"Minimum: {result}")
    else:
        print("Invalid choice.")

math_operations()


Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice (1/2/3/4): 3
Enter numbers separated by spaces: 22 33
Maximum: 33.0


4.2 Exercise on List Manipulation
1. Extract Every Other Element

In [ ]:
def extract_every_other(lst):
    return lst[::2]

# Example usage
print(extract_every_other([1, 2, 3, 4, 5, 6]))  # Output: [1, 3, 5]


[1, 3, 5]


2. Slice a Sublist

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

# Example usage
print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))  # Output: [3, 4, 5]


[3, 4, 5]


3. Reverse a List Using Slicing

In [ ]:
def reverse_list(lst):
    return lst[::-1]

# Example usage
print(reverse_list([1, 2, 3, 4, 5]))  # Output: [5, 4, 3, 2, 1]


[5, 4, 3, 2, 1]


4. Remove the First and Last Elements

In [ ]:
def remove_first_last(lst):
    return lst[1:-1]

# Example usage
print(remove_first_last([1, 2, 3, 4, 5]))  # Output: [2, 3, 4]


[2, 3, 4]


5. Get the First n Elements

In [ ]:
def get_first_n(lst, n):
    return lst[:n]

# Example usage
print(get_first_n([1, 2, 3, 4, 5], 3))  # Output: [1, 2, 3]


[1, 2, 3]


6. Extract Elements from the End

In [ ]:
def get_last_n(lst, n):
    return lst[-n:]

# Example usage
print(get_last_n([1, 2, 3, 4, 5], 2))  # Output: [4, 5]


[4, 5]


7. Extract Elements in Reverse Order

In [ ]:
def reverse_skip(lst):
    return lst[-2::-2]

# Example usage
print(reverse_skip([1, 2, 3, 4, 5, 6]))  # Output: [5, 3, 1]


[5, 3, 1]


4.3 Exercise on Nested List
1. Flatten a Nested List

In [ ]:
def flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

# Example usage
print(flatten([[1, 2], [3, 4], [5]]))  # Output: [1, 2, 3, 4, 5]


[1, 2, 3, 4, 5]


2. Accessing Nested List Elements

In [ ]:
def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element

# Example usage
print(access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))  # Output: 6


6


3. Sum of All Elements in a Nested List

In [ ]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

# Example usage
print(sum_nested([[1, 2], [3, [4, 5]], 6]))  # Output: 21


21


4. Remove Specific Element from a Nested List

In [ ]:
def remove_element(lst, elem):
    return [[x for x in sublist if x != elem] for sublist in lst]

# Example usage
print(remove_element([[1, 2], [3, 2], [4, 5]], 2))  # Output: [[1], [3], [4, 5]]


[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List

In [ ]:
def find_max(lst):
    max_elem = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_elem = max(max_elem, find_max(item))
        else:
            max_elem = max(max_elem, item)
    return max_elem

# Example usage
print(find_max([[1, 2], [3, [4, 5]], 6]))  # Output: 6


6


6. Count Occurrences of an Element in a Nested List

In [ ]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

# Example usage
print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))  # Output: 3


3


7. Flatten a List of Lists of Lists

In [ ]:
def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

# Example usage
print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))  # Output: [1, 2, 3, 4, 5, 6, 7, 8]


[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average

In [ ]:
def average_nested(lst):
    total, count = 0, 0
    for item in lst:
        if isinstance(item, list):
            sub_total, sub_count = average_nested(item)  # Get total and count from sublist
            total += sub_total
            count += sub_count
        else:
            total += item
            count += 1
    return (total, count) if count else (0, 0)  # Return total and count as a tuple

# Wrapper function to get only the average
def get_average(lst):
    total, count = average_nested(lst)
    return total / count if count else 0

# Example usage
print(get_average([[1, 2], [3, 4], [5, 6]]))  # Output: 3.5


3.5


5 About NumPy
Problem - 1: Array Creation

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("Ones Array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill_value
filled_array = np.full((3, 3), fill_value=7)
print("Filled Array:\n", filled_array)

# 4. Return a new array of zeros with the same shape and type as a given array
original_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(original_array)
print("Zeros Like Array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(original_array)
print("Ones Like Array:\n", ones_like_array)

# 6. Convert a list to a NumPy array
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("Array from List:\n", array_from_list)


Empty Array:
 [[6.86235377e-310 2.53701128e-316]
 [2.84941606e-310 0.00000000e+000]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Filled Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros Like Array:
 [[0 0 0]
 [0 0 0]]
Ones Like Array:
 [[1 1 1]
 [1 1 1]]
Array from List:
 [1 2 3 4]


Problem - 2: Array Manipulation

In [ ]:
# 1. Create an array with values ranging from 10 to 49
range_array = np.arange(10, 50)
print("Range Array:\n", range_array)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array Mean:", mean_value)

# 5. Create a 10x10 array with random values and find the minimum and maximum values
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("Min Value:", min_value, "Max Value:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("Modified Zero Array:\n", zero_array)

# 7. Reverse an array
array_to_reverse = np.array([1, 2, 0, 0, 4, 0])
reversed_array = array_to_reverse[::-1]
print("Reversed Array:\n", reversed_array)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("Border Array:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard Pattern:\n", checkerboard)


Range Array:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Array Mean: 0.5141332027359384
Min Value: 0.005149796109950366 Max Value: 0.9994983490934769
Modified Zero Array:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed Array:
 [0 4 0 0 2 1]
Border Array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Checkerboard Pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations

In [ ]:
# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
sum_xy = x + y
print("Sum of x and y:\n", sum_xy)

# 2. Subtract the two arrays
diff_xy = x - y
print("Difference of x and y:\n", diff_xy)

# 3. Multiply the array with an integer
multiplied_x = x * 3
print("Multiplied x by 3:\n", multiplied_x)

# 4. Find the square of each element of the array
squared_x = np.square(x)
print("Square of each element in x:\n", squared_x)

# 5. Find the dot product between v and w; x and v; x and y
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot Product v and w:", dot_vw)
print("Dot Product x and v:\n", dot_xv)
print("Dot Product x and y:\n", dot_xy)

# 6. Concatenate x and y along row and v and w along column
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.column_stack((v, w))
print("Concatenate x and y along row:\n", concat_xy_row)
print("Concatenate v and w along column:\n", concat_vw_col)

# 7. Concatenate x and v; explain any error
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("Error:", e)
    print("Explanation: The shapes of x and v are not compatible for concatenation along axis 0.")


Sum of x and y:
 [[ 6  8]
 [10 13]]
Difference of x and y:
 [[-4 -4]
 [-4 -3]]
Multiplied x by 3:
 [[ 3  6]
 [ 9 15]]
Square of each element in x:
 [[ 1  4]
 [ 9 25]]
Dot Product v and w: 219
Dot Product x and v:
 [29 77]
Dot Product x and y:
 [[19 22]
 [50 58]]
Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
 [[ 9 11]
 [10 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: The shapes of x and v are not compatible for concatenation along axis 0.


Problem - 4: Matrix Operations

In [ ]:
# Given arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^(-1) = I
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("A * A^(-1):\n", identity_check)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)
print("AB != BA:", not np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(np.dot(A, B))
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T:\n", AB_T)
print("B^T * A^T:\n", B_T_A_T)
print("(AB)^T == B^T * A^T:", np.array_equal(AB_T, B_T_A_T))

# Solve the system of linear equations using inverse method
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_matrix = np.array([-1, -3, 9])
X = np.linalg.solve(A_matrix, B_matrix)
print("Solution X:\n", X)

# Solve using np.linalg.inv
A_inv_matrix = np.linalg.inv(A_matrix)
X_inv = np.dot(A_inv_matrix, B_matrix)
print("Solution X using inverse:\n", X_inv)


A * A^(-1):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB != BA: True
(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
(AB)^T == B^T * A^T: True
Solution X:
 [ 2.  1. -2.]
Solution X using inverse:
 [ 2.  1. -2.]


10.2 Experiment: How Fast is NumPy?

In [ ]:
import time

# Element-wise Addition
size = 1000000
list_a = list(range(size))
list_b = list(range(size))

start_time = time.time()
result_list = [a + b for a, b in zip(list_a, list_b)]
end_time = time.time()
list_time = end_time - start_time
print(f"List Addition Time: {list_time:.5f} seconds")

array_a = np.array(list_a)
array_b = np.array(list_b)

start_time = time.time()
result_array = array_a + array_b
end_time = time.time()
array_time = end_time - start_time
print(f"Array Addition Time: {array_time:.5f} seconds")

# Element-wise Multiplication
start_time = time.time()
result_list = [a * b for a, b in zip(list_a, list_b)]
end_time = time.time()
list_time = end_time - start_time
print(f"List Multiplication Time: {list_time:.5f} seconds")

start_time = time.time()
result_array = array_a * array_b
end_time = time.time()
array_time = end_time - start_time
print(f"Array Multiplication Time: {array_time:.5f} seconds")

# Dot Product
start_time = time.time()
result_list = sum(a * b for a, b in zip(list_a, list_b))
end_time = time.time()
list_time = end_time - start_time
print(f"List Dot Product Time: {list_time:.5f} seconds")

start_time = time.time()
result_array = np.dot(array_a, array_b)
end_time = time.time()
array_time = end_time - start_time
print(f"Array Dot Product Time: {array_time:.5f} seconds")

# Matrix Multiplication
matrix_a = np.random.rand(1000, 1000)
matrix_b = np.random.rand(1000, 1000)

start_time = time.time()
result_matrix_list = [[sum(a * b for a, b in zip(row_a, col_b)) for col_b in zip(*matrix_b)] for row_a in matrix_a]
end_time = time.time()
list_time = end_time - start_time
print(f"List Matrix Multiplication Time: {list_time:.5f} seconds")

start_time = time.time()
result_matrix_array = np.dot(matrix_a, matrix_b)
end_time = time.time()
array_time = end_time - start_time
print(f"Array Matrix Multiplication Time: {array_time:.5f} seconds")


List Addition Time: 0.08534 seconds
Array Addition Time: 0.00563 seconds
List Multiplication Time: 0.07172 seconds
Array Multiplication Time: 0.00478 seconds
List Dot Product Time: 0.09454 seconds
Array Dot Product Time: 0.00175 seconds
List Matrix Multiplication Time: 296.69567 seconds
Array Matrix Multiplication Time: 0.08100 seconds
